on:
  push:
    branches:
      - main
  schedule:
    - cron: "30 15 * * *"
  workflow_dispatch:

jobs:
  github-actions-cache-cleaner:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3.1.0
      - uses: dev-hato/github-actions-cache-cleaner@v0
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
