name: Branch Cleanup

on:
  pull_request:
    types: [closed]

jobs:
  cleanup:
    runs-on: ubuntu-latest
    steps:
      - name: Delete Branch
        uses: jessfraz/branch-cleanup-action@master
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
